server:
  port: 8080

app:
  cache:
    size: 365
  rest:
    api:
      prefix: /api

cbr:
  url: "https://cbr.ru/scripts/XML_daily.asp"

moex:
  url: https://www.moex.com/export/derivatives/currency-rate.aspx